version: '3'

services:
  mysql:
    image: mysql:8
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=testdb"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - default
  build:
    image: maven:latest
    working_dir: /app
    user: 1000:1000
    volumes:
      - .:/app
      - $HOME/.m2/repository:/m/repository
    command: mvn package
    depends_on:
      - mysql
    networks:
      - default

  deploy:
    image: openjdk:17-oracle
    working_dir: /app
    user: 1000:1000
    volumes:
      - .:/app
    command: java -jar target/voting-session-0.0.1-SNAPSHOT.jar
    depends_on:
      - build
      - mysql
    networks:
      - default
networks:
  default:
    driver: bridge